# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Docker Login
      inputs:
        containerRegistry: 'SebugDockerHub'
        command: login

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/PCPersonnel/Dockerfile'
        tags: $(tag)

    - script: cd $(Build.SourcesDirectory)/PCPersonnel && docker build -t sebug/pc-personnel:$(Build.BuildId) .

    - task: Docker@2
      displayName: Push pc personnel
      inputs:
        containerRegistry: 'SebugDockerHub'
        repository: 'sebug/pc-personnel'
        command: 'push'
        tags: $(tag)


