version: '3.4'

services:
  pcpersonnel:
    image: sebug/pc-personnel:507
    env_file:
      - ./pcpersonnel.env
      - ./connectionstring.env
    networks:
      - postgres
    ports:
      - "9085:80"

  postgresql:
    image: sebug/postgresql-pcpersonnel:507
    ports:
      - "5432:5432"
    env_file:
      - ./database.env
    networks:
      - postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4@sha256:17d0443fc8ece58f70e8d5b1ff4aa97b04235b43174c571da937b7a888a87826
    env_file:
      - ./pgadmin_defaults.env
    networks:
      - postgres
    ports:
      - "9086:80"

networks:
  postgres:
    driver: bridge
      
volumes:
  db-data:
    driver: local


